/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sew4b_projekt_1920_drihox;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author drihox15
 */
public class ProjektGUI extends javax.swing.JFrame {
    String server;
    String port;
    String user;
    String pwd;
    String db;
    String url;
    Connection con=null;
    DatabaseMetaData md=null;
    DefaultTableModel tm;
    PreparedStatement stmt;
    
    public ProjektGUI() {
        initComponents();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
        } 
        catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(this, "Fehler beim Herunterladen des Treibers", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
        
        btnDisconnect.setEnabled(false);
        tabData.setEnabled(false);
        btnDelete.setEnabled(false);
        btnInsert.setEnabled(false);
        btnUpdate.setEnabled(false);
        cbxTables.setEnabled(false);
        tabData.setModel(new DefaultTableModel());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbServer = new javax.swing.JLabel();
        lbPort = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        lbDB = new javax.swing.JLabel();
        txtServer = new javax.swing.JTextField();
        txtPort = new javax.swing.JTextField();
        txtDB = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        cbxTables = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabData = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnConnect = new javax.swing.JButton();
        btnDisconnect = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbServer.setText("Server:");

        lbPort.setText("Port:");

        lbUsername.setText("Username:");

        lbPassword.setText("Password:");

        lbDB.setText("Database:");

        txtServer.setText("localhost");

        txtPort.setText("3306");

        txtDB.setText("sew_4b_projekt");

        txtUsername.setText("root");

        cbxTables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTablesActionPerformed(evt);
            }
        });

        tabData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabData);
        if (tabData.getColumnModel().getColumnCount() > 0) {
            tabData.getColumnModel().getColumn(0).setResizable(false);
            tabData.getColumnModel().getColumn(1).setResizable(false);
            tabData.getColumnModel().getColumn(2).setResizable(false);
        }

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        btnDisconnect.setText("Disconnect");
        btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisconnectActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnInsert)
                .addGap(118, 118, 118)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbServer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtServer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(txtUsername)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPort)
                        .addGap(18, 18, 18)
                        .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lbPassword)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbxTables, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConnect)
                    .addComponent(btnDisconnect))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbServer)
                    .addComponent(lbUsername)
                    .addComponent(lbDB)
                    .addComponent(txtServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConnect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPort)
                    .addComponent(lbPassword)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDisconnect))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        server=txtServer.getText();
        port=txtPort.getText();
        user=txtUsername.getText();
        pwd=txtPassword.getText();
        db=txtDB.getText();
        url="jdbc:mysql://"+server+":"+port+"/"+db;
        
        try{
            con=DriverManager.getConnection(url, user, pwd);
            
            btnDisconnect.setEnabled(true);
            tabData.setEnabled(true);
            btnDelete.setEnabled(true);
            btnInsert.setEnabled(true);
            btnUpdate.setEnabled(true);
            cbxTables.setEnabled(true);
            
            txtDB.setEnabled(false);
            txtPassword.setEnabled(false);
            txtPort.setEnabled(false);
            txtServer.setEnabled(false);
            txtUsername.setEnabled(false);
            btnConnect.setEnabled(false);
        } 
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Fehler bei der Verbindung", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
        try{
            md=con.getMetaData();
            ResultSet rs=md.getTables(null, null, null, null);
            while(rs.next()){
                cbxTables.addItem(rs.getString("TABLE_NAME"));
            }
        } 
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Fehler bei der Tabellenanzeige", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnectActionPerformed
        try{
            con.close();
            
            btnDisconnect.setEnabled(false);
            tabData.setEnabled(false);
            btnDelete.setEnabled(false);
            btnInsert.setEnabled(false);
            btnUpdate.setEnabled(false);
            cbxTables.setEnabled(false);
            cbxTables.removeAllItems();
            
            txtDB.setEnabled(true);
            txtPassword.setEnabled(true);
            txtPort.setEnabled(true);
            txtServer.setEnabled(true);
            txtUsername.setEnabled(true);
            btnConnect.setEnabled(true);
            tabData.setModel(new DefaultTableModel());
        }
        catch(SQLException ex){
            System.out.println("Fehler beim Schliessen der Verbindung.");
        }
    }//GEN-LAST:event_btnDisconnectActionPerformed

    private void cbxTablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTablesActionPerformed
            try{
                String docSelect="SELECT * FROM doctor;";
                String deptSelect="SELECT * FROM department;";
                if(cbxTables.getSelectedItem()!=null){
                    tm=new DefaultTableModel();
                    if(cbxTables.getSelectedItem().toString().equals("department")){
                        tm.addColumn("deptID");
                        tm.addColumn("name");
                        tm.addColumn("size");
                        stmt=con.prepareStatement(deptSelect);
                        ResultSet rs=stmt.executeQuery();
                        while(rs.next()){
                            Object o[]={
                                rs.getInt("deptID"),
                                rs.getString("name"),
                                rs.getString("size")
                            };
                            tm.addRow(o);
                        }
                    }
                    else{
                        tm.addColumn("ID");
                        tm.addColumn("vorname");
                        tm.addColumn("nachanme");
                        tm.addColumn("deptID");
                        stmt=con.prepareStatement(docSelect);
                        ResultSet rs=stmt.executeQuery();
                        while(rs.next()){
                            Object o[]={
                                rs.getInt("ID"),
                                rs.getString("vorname"),
                                rs.getString("nachname"),
                                rs.getInt("deptID")
                            };
                            tm.addRow(o);
                        }
                    }
                    tabData.setModel(tm);
                }
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Fehler beim Select-Statement.", "Fehler", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_cbxTablesActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String toDeleteID=JOptionPane.showInputDialog(this,"Enter ID: ");
        PreparedStatement st=null;
        try{
            if(!toDeleteID.equals(null) && toDeleteID.matches("[0-9]+")){
                if(cbxTables.getSelectedItem()!=null){
                    if(cbxTables.getSelectedItem().toString().equals("department")){
                        st=con.prepareStatement("DELETE FROM department WHERE deptID=?");
                        st.setInt(1,Integer.parseInt(toDeleteID));
                    }
                    else{
                        st=con.prepareStatement("DELETE FROM doctor WHERE ID=?");
                        st.setInt(1,Integer.parseInt(toDeleteID));
                    }
                    st.executeUpdate(); 
                }
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Fehler beim Delete-Statement.", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
        catch(NullPointerException ex){
            
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        String[] buttons = {"Doctor", "Department"};
        int result=JOptionPane.showOptionDialog(this, "Tabelle wählen", "Insert",
        JOptionPane.INFORMATION_MESSAGE, 0, null, buttons, null);
        String insert="";
        PreparedStatement st=null;
        try{
            if(cbxTables.getSelectedItem()!=null){
                if(result==0){
                    insert="INSERT INTO doctor(vorname,nachname,deptID) VALUES(?,?,?)";
                    st=con.prepareStatement(insert);
                    
                    String vn=JOptionPane.showInputDialog(this,"Name:");
                    String nn=JOptionPane.showInputDialog(this,"Lastname:");
                    String dId=JOptionPane.showInputDialog(this,"DeptID");
                    if(!vn.equals("") && !nn.equals("") && !dId.equals("") && dId.matches("[0-9]+")){
                        st.setString(1, vn);
                        st.setString(2, nn);
                        st.setInt(3, Integer.parseInt(dId));
                    }
                }
                else if(result==1){
                    insert="INSERT INTO department(name,size) VALUES(?,?)";
                    st=con.prepareStatement(insert);
                    
                    String n=JOptionPane.showInputDialog(this,"Name:");
                    String s=JOptionPane.showInputDialog(this,"Size:");
                    
                    if(!n.equals("") && !s.equals("") && s.matches("[0-9]+")){
                        st.setString(1, n);
                        st.setInt(2, Integer.parseInt(s));
                    }
                }
                st.executeUpdate();
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "Fehler beim Insert-Statement.", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisconnect;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cbxTables;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDB;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPort;
    private javax.swing.JLabel lbServer;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JTable tabData;
    private javax.swing.JTextField txtDB;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtServer;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
